# docker-compose.yml
services:
  build_pieldetoro_dat:
    build:
      context: .
      dockerfile: Dockerfile
    image: build_pieldetoro
    volumes:
      - ./static:/compile # Carpeta compartida para resultados
      - ./src:/src
    working_dir: /compile
    command: /bin/bash -c -e "./build.sh  "

  build_pieldetoro_exe:
    build:
      context: .
      dockerfile: Dockerfile
    image: build_pieldetoro
    depends_on:
      build_pieldetoro_dat:
        condition: service_completed_successfully
    volumes:
      - ./src:/compile/src         # Codigo fuente
      - ./setup:/compile/setup     # Setup allegro
      - ./dist:/compile/dist       # Carpeta compartida para resultados
      - ./static:/compile/static   # static folder
    working_dir: /compile
    command: /bin/bash -c -e "./build_project.sh"
